//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class BATCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BATCH()
        {
            this.PARTICIPANTs = new ObservableCollection<PARTICIPANT>();
        }
    
        public int BatchID { get; set; }
        public Nullable<System.DateTime> BatchStartDate { get; set; }
        public Nullable<System.DateTime> BatchEndDate { get; set; }
        public string Stream { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string BatchDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<PARTICIPANT> PARTICIPANTs { get; set; }
        public virtual FACULTY FACULTY { get; set; }
    }
}
